import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ShadeProvider } from "@/context/useShade";
import { CartProvider } from "@/context/useCart";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kiki Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <CartProvider>
          <ShadeProvider>
            <>
              <ScrollToTop />
              <div className="flex flex-col min-h-screen bg-white font-sans">
                <Navbar />
                <main className="flex-grow w-full">{children}</main>
                <Footer />
              </div>
            </>
          </ShadeProvider>
        </CartProvider>
      </body>
      <GoogleAnalytics gaId="G-EKVNLCL1MD" />
    </html>
  );
}
